export const ROUTES = {
  HOME: '/',
  PRODUCT: `/pages/products`,
  CHECKOUT: '/pages/checkout',
  CONTACT: '/pages/contact-us',
  TERMS: '/pages/terms',
  PRIVACY: '/pages/privacy',
  FAQ: '/pages/faq',
  FORGET_PASSWORD: '/pages/forget-password',
  CHANGE_PASSWORD: '/pages/my-account/change-password',
  ACCOUNT: '/pages/my-account/account-settings',
  ORDERS: '/pages//my-account/orders',
  ACCOUNT_SETTING: '/pages/my-account/account-settings',
  ADDRESS: '/pages/my-account/address',
  HELP_CENTER: '/pages/my-account/help-center',
  LEGAL_NOTICE: '/pages/my-account/legal-notice',
  NOTIFICATION: '/pages/my-account/notification',
  SHOPS: '/pages/shops',
  LOGIN: '/pages/signin',
  SIGN_UP: '/pages/signup',
  SEARCH: '/pages/search',
  PRODUCTS: '/pages/products',
  BUNDLE: '/pages/bundles',
  CATEGORY: '/pages/category',
  ORDER: '/pages/complete-order',
  WISHLIST: '/pages/my-account/wishlist',
};
